# Generated by Django 6.0.3 on 2026-03-22 10:07

import account.managers.users
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('phone_activated', models.BooleanField(blank=True, default=True, verbose_name='Номер телефона активирован')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в')),
                ('role', models.CharField(choices=[('player', 'Игрок'), ('coach', 'Тренер'), ('organizer', 'Организатор'), ('admin', 'Админ')], default='player', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', account.managers.users.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, verbose_name='Пол')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('elo_rating', models.IntegerField(default=700, verbose_name='ELO рейтинг')),
                ('classic_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Классический рейтинг')),
                ('photo', models.ImageField(upload_to='profiles/', verbose_name='Фото профиля')),
                ('experience_years', models.IntegerField(verbose_name='Опыт(лет)')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Сертификаты')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка в час')),
                ('total_traings', models.IntegerField(default=0, verbose_name='Проведено игр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Профиль тренера',
                'verbose_name_plural': 'Профили тренеров',
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, verbose_name='Пол')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('elo_rating', models.IntegerField(default=700, verbose_name='ELO рейтинг')),
                ('classic_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Классический рейтинг')),
                ('photo', models.ImageField(upload_to='profiles/', verbose_name='Фото профиля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('total_games', models.IntegerField(default=0, verbose_name='Организовано игр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Профили организаторов',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, verbose_name='Пол')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('elo_rating', models.IntegerField(default=700, verbose_name='ELO рейтинг')),
                ('classic_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Классический рейтинг')),
                ('photo', models.ImageField(upload_to='profiles/', verbose_name='Фото профиля')),
                ('skill_level', models.PositiveSmallIntegerField(choices=[(1, 'Начальный'), (2, 'Начальный +'), (3, 'Средний -'), (4, 'Средний'), (5, 'Средний +'), (6, 'Высокий -'), (7, 'Высокий'), (8, 'Высокий +'), (9, 'Профи')], default=4, verbose_name='Уровень навыков')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Диагональный'), (2, 'Связующий'), (3, 'Центральный блокирующий'), (4, 'Доигровщик'), (5, 'Универсал'), (6, 'Либеро')], default=5, verbose_name='Позиция')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='Заполненность профиля')),
                ('total_games', models.IntegerField(default=0, verbose_name='Игр сыграно')),
                ('total_tournament', models.IntegerField(default=0, verbose_name='Игра на турнире сыграно')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
                'indexes': [models.Index(fields=['skill_level'], name='account_pla_skill_l_da812d_idx'), models.Index(fields=['elo_rating'], name='account_pla_elo_rat_40fea2_idx')],
            },
        ),
    ]
