# Generated by Django 6.0.3 on 2026-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blacklistedtoken_emailconfirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='total_tournament',
            field=models.IntegerField(default=0, verbose_name='Игр на турнире сыграно'),
        ),
    ]
