# Generated by Django 6.0.3 on 2026-05-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_coachprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizerprofile',
            options={'verbose_name': 'Профиль организатора', 'verbose_name_plural': 'Профили организаторов'},
        ),
    ]
