# Generated by Django 6.0.3 on 2026-05-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='last_read_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 10, 17, 0, 136771, tzinfo=datetime.timezone.utc), verbose_name='Послднее прочтение'),
        ),
    ]
