# Generated by Django 6.0.3 on 2026-05-06 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmembership_last_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='last_read_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 11, 42, 58, 343431, tzinfo=datetime.timezone.utc), verbose_name='Послднее прочтение'),
        ),
    ]
