# Generated by Django 6.0.3 on 2026-05-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmembership_last_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Послднее прочтение'),
        ),
    ]
