# Generated by Django 6.0.3 on 2026-03-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('etc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('descrption', models.TextField(blank=True, verbose_name='Описание')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность (мин)')),
                ('capacity', models.IntegerField(default=12, verbose_name='Вместимость')),
                ('booked_count', models.IntegerField(default=0, verbose_name='Записано')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('skill_level', models.PositiveSmallIntegerField(choices=[(1, 'Начальный'), (2, 'Начальный +'), (3, 'Средний -'), (4, 'Средний'), (5, 'Средний +'), (6, 'Высокий -'), (7, 'Высокий'), (8, 'Высокий +'), (9, 'Профи')], default=4, verbose_name='Требуемый уровень')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Без ограничений'), (1, 'Только мужчины'), (2, 'Только женщины'), (3, 'Смешанная')], default=0, verbose_name='Пол')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'Запись открыта'), (3, 'Идет'), (4, 'Завершено'), (5, 'Отменено')], default=0, verbose_name='Статус')),
                ('elo_rating_change', models.IntegerField(blank=True, null=True, verbose_name='Иземенение ELO')),
                ('is_tournament', models.BooleanField(default=False, verbose_name='Турнирная игра')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='etc.location', verbose_name='Место проведения')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='account.organizerprofile', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Записан'), (2, 'Подтверждён'), (3, 'Присутствовал'), (4, 'Не пришел'), (5, 'Отменил')], default=1, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки')),
                ('elo_before', models.IntegerField(blank=True, null=True, verbose_name='ELO до')),
                ('elo_after', models.IntegerField(blank=True, null=True, verbose_name='ELO после')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participants', to='game.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participants', to='account.playerprofile', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Участник игры',
                'verbose_name_plural': 'Участники игр',
            },
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating_game', models.IntegerField(default=5, verbose_name='Рейтинг игры')),
                ('rating_organizer', models.IntegerField(default=5, verbose_name='Рейтинг организатора')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='game.game', verbose_name='Игра')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to='account.organizerprofile', verbose_name='Организатор')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to='account.playerprofile', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Отзыв об игре',
                'verbose_name_plural': 'Отзывы об играх',
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'date_time'], name='game_game_status_90801f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameparticipant',
            unique_together={('game', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='gamereview',
            unique_together={('game', 'player')},
        ),
    ]
