# Generated by Django 6.0.3 on 2026-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='descrption',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
