# Generated by Django 6.0.3 on 2026-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_descrption_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Запись открыта'), (2, 'Запись окончена'), (3, 'Идёт'), (4, 'Завершено'), (5, 'Отменено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Записан'), (2, 'Подтверждён'), (3, 'Присутствовал'), (4, 'Не пришел')], default=1, verbose_name='Статус'),
        ),
    ]
