# Generated by Django 6.0.3 on 2026-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('venue_type', models.PositiveSmallIntegerField(choices=[(1, 'Спортивный комплекс'), (2, 'Школьный зал'), (3, 'Университетский зал'), (4, 'Частный клуб'), (5, 'Открытая площадка'), (6, 'Пляж')], verbose_name='Тип зала')),
                ('surface_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Паркет'), (2, 'Синтетика'), (3, 'Песок'), (4, 'Бетон'), (5, 'Резина'), (6, 'Другое')], null=True, verbose_name='Покрытие')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='etc_locatio_latitud_1c91c6_idx')],
            },
        ),
    ]
